name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo HitHub Actions!
on: [push]
jobs:
  hola-mundo: 
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hola_mundo.py
